apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tribee
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: wildcard-cloudflare-issuer-prod
    # acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - "*.tribee.vn"
        - "tribee.vn"
      secretName: wildcard-certificate-cloudflare
  rules:
    - host: "*.tribee.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tribee-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: tribee-backend
                port:
                  number: 80
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: tribee-backend
                port:
                  number: 80
    - host: "tribee.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tribee-wp
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: tribee-backend
                port:
                  number: 80
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: tribee-backend
                port:
                  number: 80
