apiVersion: v1
kind: Service
metadata:
  name: carx-agent-web
  labels:
    type: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    deployment: carx-agent-web
