apiVersion: v1
kind: Service
metadata:
  name: tribes-frontend
  labels:
    type: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    deployment: tribes-frontend
