apiVersion: apps/v1
kind: Deployment
metadata:
  name: tribes-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: tribes-frontend
  template:
    metadata:
      labels:
        deployment: tribes-frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: tribes-frontend
          image: eastplayers/tribes-frontend:staging-0.1.1
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /
              port: 3000
          ports:
            - containerPort: 80
              protocol: TCP

