apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carx-agent-web
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - agent-carx.eastplayers.io
      secretname: tribes-cert-secret
  rules:
    - host: agent-carx.eastplayers.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carx-agent-web
                port:
                  number: 80
